import { Metadata } from "next"
import { Footer } from "./components/Footer"

export const metadata: Metadata = {
  title: 'Royal',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
      <section
        className={`min-h-screen  overflow-x-hidden  `}
      >
        {children}
<Footer />
      </section>
 
  )
}