import { Metadata } from "next"
import { Footer } from "./components/Footer"
import { NavBar } from "./components/NavBar"

export const metadata: Metadata = {
  title: 'Royal',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
      <section
        className={ ``}
      >
        <NavBar/>
        {children}
        <Footer />
      </section>
 
  )
}