import { Metadata } from "next"
import { Footer } from "./components/Footer"
import { NavBar } from "./components/NavBar"
import { ViewTransitions } from "next-view-transitions"

export const metadata: Metadata = {
  title: 'Royal',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>

      <section
        className={ ``}
        >
        <NavBar/>
        {children}
        <Footer />
      </section>
     </ViewTransitions>
 
  )
}