import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

 
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'fizzi',
  description: 'Generated by create next app',
}

const alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${alpino.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
