import { Metadata } from "next"
 

export const metadata: Metadata = {
  title: 'Royal',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
 

      <section
        className={ ``}
        >
       
         {children}
      </section>
    
 
  )
}