 
import localFont from 'next/font/local'
 
import Header from '@/components/Header'
import ViewCanvas from '@/components/ViewCanvas'
import { Metadata } from 'next'

 
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'fizzi',
  description: 'Generated by create next app',
}

const alpino = localFont({
  // src: "../../public/fonts/Alpino-Variable.woff2",
  src: "../../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
 
      <main
        className={`min-h-screen bg-yellow-300 overflow-x-hidden ${alpino.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <ViewCanvas/>
      </main>
    
  )
}
